### ISSUE TITLE
Not Working on 9.1.1

### ISSUE THREAD

**Issue by doubleaa93** [shahabhameed/TeamCity_TargetProcessIntegration#1]
Installed using the zip inside the target folder but it does not show up as an option when creating a new issue tracker connection

**Comment by shahabhameed** [comment]
its now solved, tested on 9.1.5
It was related to : https://youtrack.jetbrains.com/issue/TW-41508

https://confluence.jetbrains.com/display/TCD9/Open+API+Changes#OpenAPIChanges-issueTrackersChanges91
